// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking_lot_management_system_uge_10_11.Data;

#nullable disable

namespace Parking_lot_management_system_uge_10_11.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251117132159_smallFix")]
    partial class smallFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.Lot", b =>
                {
                    b.Property<int>("LotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LotID"));

                    b.Property<int>("Lot_types_ID")
                        .HasColumnType("int");

                    b.Property<bool>("Occupied_Status")
                        .HasColumnType("bit");

                    b.Property<int>("Structur_ID")
                        .HasColumnType("int");

                    b.HasKey("LotID");

                    b.HasIndex("Lot_types_ID");

                    b.HasIndex("Structur_ID");

                    b.ToTable("lots");
                });

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.Lot_History", b =>
                {
                    b.Property<int>("Lot_History_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lot_History_ID"));

                    b.Property<float?>("Charged")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Entry_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Exit_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("License_PLate_Numbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lot_ID")
                        .HasColumnType("int");

                    b.HasKey("Lot_History_ID");

                    b.HasIndex("Lot_ID");

                    b.ToTable("lot_Histories");
                });

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.Lot_types", b =>
                {
                    b.Property<int>("Lot_typesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lot_typesID"));

                    b.Property<float>("Price_Multiplier")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Lot_typesID");

                    b.ToTable("lot_Types");
                });

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.Organisation", b =>
                {
                    b.Property<int>("OrganisationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganisationID"));

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganisationID");

                    b.ToTable("Organisation");
                });

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.Parking_Lot_Structur", b =>
                {
                    b.Property<int>("Parking_lot_Structur_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Parking_lot_Structur_ID"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("BasePrice")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("Total_Available_Lots")
                        .HasColumnType("int");

                    b.Property<int>("Total_Occupied_Lots")
                        .HasColumnType("int");

                    b.HasKey("Parking_lot_Structur_ID");

                    b.HasIndex("OrganisationId");

                    b.ToTable("parking_Lot_Structurs");
                });

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.User_Types", b =>
                {
                    b.Property<int>("User_TypesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_TypesID"));

                    b.Property<string>("User_TypesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_TypesID");

                    b.ToTable("user_Types");
                });

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("UserTypeID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.Lot", b =>
                {
                    b.HasOne("Parking_lot_management_system_uge_10_11.Models.Lot_types", "Lot_types")
                        .WithMany()
                        .HasForeignKey("Lot_types_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_lot_management_system_uge_10_11.Models.Parking_Lot_Structur", "Parking_Lot_Structur")
                        .WithMany()
                        .HasForeignKey("Structur_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot_types");

                    b.Navigation("Parking_Lot_Structur");
                });

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.Lot_History", b =>
                {
                    b.HasOne("Parking_lot_management_system_uge_10_11.Models.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("Lot_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.Parking_Lot_Structur", b =>
                {
                    b.HasOne("Parking_lot_management_system_uge_10_11.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Parking_lot_management_system_uge_10_11.Models.Users", b =>
                {
                    b.HasOne("Parking_lot_management_system_uge_10_11.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_lot_management_system_uge_10_11.Models.User_Types", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("UserType");
                });
#pragma warning restore 612, 618
        }
    }
}
